language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.1
  - ruby-head
  - rbx-2.1.1
  - rbx
  - jruby-19mode # JRuby in 1.9 mode
  - jruby-head
matrix:
  allow_failures:
    - rvm: jruby-19mode
    - rvm: jruby-head
